version : '3.7'
services :
  licensingservice : # 시작한 서비스에 레이블을 적용
    image : licensing-service # 로컬 도커 저장소 -> 도커허브 순 검색
    ports :
      - "8080:8080" # 포트번호 정의
    environment :
      - "SPRING_PROFILES_ACTIVE=dev" # 환경 변수 전달
    networks :
      backend : # 네트워크 이름 지정
        aliases :
          - "licenseservice" # 네트워크상의 서비스에 대한 대체 호스트 이름 지정

networks :
  backend :
    driver : bridge